renew-ssl-certs: add check_not_empty()

diff --git a/.github/workflows/renew-ssl-certs.yml b/.github/workflows/renew-ssl-certs.yml
--- a/.github/workflows/renew-ssl-certs.yml
+++ b/.github/workflows/renew-ssl-certs.yml
@@ -76,11 +76,21 @@ jobs:
 
       - name: Write certificate into Vault Server
         run: |
+          set -x
           export VAULT_ADDR=${VAULT_URL}
+          export VAULT_TOKEN=${VAULT_TOKEN}
           export CERT_PATH="certs/${DOMAIN}"
-
+          # 检查参数是否为空
+          check_not_empty() {
+            if [[ -z $1 ]]; then
+              echo "Error: $2 is empty. Please provide a value."
+              exit 1
+            fi
+          }
+          check_not_empty "$VAULT_URL" "VAULT_URL"
+          check_not_empty "$VAULT_TOKEN" "VAULT_TOKEN"
+          check_not_empty "$DOMAIN" "DOMAIN"
           # Write Certificate and Private Key to Vault
-
           vault login ${VAULT_TOKEN}
           vault secrets enable -path=certs kv || true
           vault kv put ${CERT_PATH}                             \
